# Computational Methods in Ordinary Differential Equations

*Dr Jon Shiach, Department of Computing and Mathematics, Manchester Metropolitan University*

---
# Direct Methods for Solving Linear Systems of Equations

#### Learning outcomes

On successful completion of this page readers will be able to:

- Apply [LU decomposition](#LU-decomposition) to factorise a square matrix into a product of a lower triangular and upper triangular matrices.
- Apply [Crout's method](#Crout's-method) for solving a linear system of equations using LU decomposition.
- Solve a linear system of equations using LU decomposition with [partial pivoting](#Partial-pivoting).
- Apply [Cholesky decomposition](#Cholesky-decomposition) to factorise a positive definite matrix into a product of a lower triangular matrix and its transpose.
- Solve a linear system of equations using the [Cholesky-Crout method](#The-Cholesky-Crout-method).

## LU decomposition

[**LU decomposition**](https://en.wikipedia.org/wiki/LU_decomposition) (also known as **LU factorisation**) is a procedure for factorising a square matrix $A$ into the product of a **lower triangular** matrix $L$ and an **upper triangular** matri U such that

$$A = L U.$$

The advantage of writing a matrix as a product of $L$ and $U$ is that the solution to a triangular set of equations is easy to calculate using forward and back substitution.

Consider the LU decomposition of a $3\times 3$ matrix

\begin{align*}
    \begin{pmatrix}
        a_{11} & a_{12} & a_{13} \\
        a_{21} & a_{22} & a_{23} \\
        a_{31} & a_{32} & a_{33}
    \end{pmatrix} &=
    \begin{pmatrix}
        \ell_{11} & 0 & 0 \\
        \ell_{21} & \ell_{22} & 0 \\
        \ell_{31} & \ell_{32} & \ell_{33}
    \end{pmatrix}
    \begin{pmatrix}
        u_{11} & u_{12} & u_{13} \\
        0 & u_{22} & u_{23} \\
        0 & 0 & u_{33}
    \end{pmatrix} \\ &=
    \begin{pmatrix}
        \ell_{11} u_{11} & \ell_{11} u_{12} & \ell_{11} u_{13} \\
        \ell_{21} u_{11} & \ell_{21} u_{12} + \ell_{22} u_{22} & \ell_{21}u_{13} + \ell_{22} u_{23} \\
        \ell_{31} u_{11} & \ell_{31} u_{12} + \ell_{32} u_{22} & \ell_{31} u_{13} + \ell_{32} u_{23} + \ell_{33} u_{33}
    \end{pmatrix}
\end{align*}

Which gives a system of 9 equations (one for each element in $A$) in 12 unknowns which has an infinite number of solutions. If we use the condition $\ell_{ii}=1$ then

$$\begin{pmatrix}
        a_{11} & a_{12} & a_{13} \\
        a_{21} & a_{22} & a_{23} \\
        a_{31} & a_{32} & a_{33}
    \end{pmatrix} =
    \begin{pmatrix}
        u_{11} & u_{12} & u_{13} \\
        \ell_{21} u_{11} & \ell_{21} u_{12} + u_{22} & \ell_{21}u_{13} + u_{23} \\
        \ell_{31} u_{11} & \ell_{31} u_{12} + \ell_{32} u_{22} & \ell_{31} u_{13} + \ell_{32} u_{23} + u_{33}
    \end{pmatrix}$$
      
and the elements of $L$ and $U$ can be calculated using

The elements in the lower triangular region ($i>j$) we have

$$a_{ij} = \sum_{k=1}^j \ell_{ik}u_{kj} = \ell_{ij}u_{jj} + \sum_{k=1}^{j-1} \ell_{ik}u_{kj}, ,$$

which is rerranged to

<a id="LU_lij"></a>
\begin{align*}
    \ell_{ij} &= \frac{1}{u_{jj}} \left( a_{ij} - \sum_{k=1}^{j-1} \ell_{ik} u_{kj}\right). && (1)
\end{align*}

For the elements in the upper triangular region ($i\leq j$) we have

$$a_{ij} = u_{ij} + \sum_{k=1}^{i-1} \ell_{ik}u_{kj},$$

which is rerranged to

<a id="LU_uij"></a>
\begin{align*}
    u_{ij} &= a_{ij} - \sum_{k=1}^{i-1} \ell_{ik}u_{kj}. && (2)
\end{align*}

So to calculate the LU decomposition of a square matrix $A$ we loop through each column of $A$ and calculate the elements of $L$ and $U$ for that column using equations (1) and (2), i.e., 

<a id="LU"></a>
\begin{align*}
    u_{ij} &= a_{ij} - \sum_{k=1}^{i-1} \ell_{ik}u_{kj}, && i = 1, 2, \ldots j, && (3) \\
    \ell_{ij} &= 1, && i=j,  && (4) \\
    \ell_{ij} &= \dfrac{1}{u_{jj}} \left( a_{ij} - \displaystyle\sum_{k=1}^{j-1} \ell_{ik} u_{kj}\right), && i = j+1, j+2, \ldots, n && (5)
\end{align*}

#### Example 1

Determine the LU decomposition of the following matrix

$$A = \begin{pmatrix} 1 & 3 & 0 \\ 2 & -4 & -1 \\ -3 & 1 & 2 \end{pmatrix}.$$

Column 1:

\begin{align*}
    u_{11} &= a_{11} = 1, \\
    \ell_{21} &= \frac{1}{u_{11}}(a_{21}) = \frac{1}{1}(2) = 2, \\
    \ell_{31} &= \frac{1}{u_{11}}(a_{31}) = \frac{1}{1}(-3) = -3.
\end{align*}

Column 2:

\begin{align*}
    u_{12} &= a_{12} = 3, \\
    u_{22} &= a_{22} - \ell_{21}u_{12} = -4 - 2(3) = -10, \\
    \ell_{32} &= \frac{1}{u_{22}}(a_{32} - \ell_{31}u_{12}) = \frac{1}{-10}(1 + 3(3)) = 1.
\end{align*}

Column 3:

\begin{align*}
    u_{13} &= a_{13} = 0, \\
    u_{23} &= a_{23} - \ell_{21}u_{13} = -1 - 2(0) = -1, \\
    u_{33} &= a_{33} - \ell_{31}u_{13} - \ell_{32}u_{23} = 2 + -3(0) - 1(-1) = 3.
\end{align*}

Therefore 

\begin{align*}
    L &= \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -3 & -1 & 1 \end{pmatrix}, &
    U &= \begin{pmatrix} 1 & 3 & 0 \\ 0 & -10 & -1 \\ 0 & 0 & 1 \end{pmatrix}.
\end{align*}

Checking that $L U=A$

\begin{align*}
    \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -3 & -1 & 1 \end{pmatrix}
    \begin{pmatrix} 1 & 3 & 0 \\ 0 & -10 & -1 \\ 0 & 0 & 1 \end{pmatrix} = 
    \begin{pmatrix} 1 & 3 & 0 \\ 2 & -4 & -1 \\ -3 & 1 & 2 \end{pmatrix}
\end{align*}

#### Example 2

The function defined below called `LU` calculates the LU decomposition of a square matrix `A`.

In [1]:
import numpy as np

def LU(A):
    '''
    Calculates the LU decomposition of the square matrix A
    '''
    # Initialise L and U
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))

    # Loop through columns
    for j in range(n):
        
        # Calculate u_ij for i <= j
        for i in range(j+1):
            for k in range(i):
                U[i,j] += L[i,k] * U[k,j]
            U[i,j] = (A[i,j] - U[i,j])
            
        # Calculate l_ij for i > j
        for i in range(j+1, n):
            for k in range(j):
                L[i,j] += L[i,k] * U[k,j]
            L[i,j] = (A[i,j] - L[i,j]) / U[j, j]
        
    return L, U

The code below uses the function `LU` to calculate the LU decomposition of the matrix from [example 1](#Example-1).

In [2]:
# Define matrix A
A = np.array([[ 1, 3, 0 ],
              [ 2, -4, -1 ],
              [ -3, 1, 2 ]])

# Calculate L and U
L, U = LU(A)

# Output L and U and check results
print('L = ')
print(L)
print('\nU = ')
print(U)
print('\nCheck that A - L.U = 0')
print(A - np.matmul(L, U))

L = 
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]

U = 
[[  1.   3.   0.]
 [  0. -10.  -1.]
 [  0.   0.   1.]]

Check that A - L.U = 0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
## Crout's method

Given a linear system of equations of the form $A\mathbf{x} = \mathbf{b}$ then the solution can be calculated using the LU decomposition of $A$ **Crout's method**. Since $A=LU$ then

$$LU\mathbf{x} = \mathbf{b}$$
    
Let $\mathbf{y} = U\mathbf{x}$ then

$$L \mathbf{y} = \mathbf{b},$$

$L$ is lower triangular so the solution for $L\mathbf{y}=\mathbf{b}$ is easily calculated using forward substitution. Once $\mathbf{y}$ has been calculated the solution to $U\mathbf{x} = \mathbf{y}$ is calculated using back substitution. 

The advantage of using Crout's algorithm is that once the LU decomposition of the coefficient matrix has been calculated the can be used for any values of the right-hand side vector $\mathbf{b}$ unlike Gaussian elimination where row reduction will need to be repeated for difference values of $\mathbf{b}$.

#### Example 3

Use Crout's method to solve the following linear system of equations.

$$\begin{pmatrix} 1 & 3 & 0 \\ 2 & -4 & -1 \\ -3 & 1 & 2 \end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} =
\begin{pmatrix} -7 \\ 11 \\ 1 \end{pmatrix}.$$

We saw in [example 1](#Example-1) that the $LU$ decomposition of the coefficient matrix was

\begin{align*}
    L &= \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -3 & -1 & 1 \end{pmatrix}, &
    U &= \begin{pmatrix} 1 & 3 & 0 \\ 0 & -10 & -1 \\ 0 & 0 & 1 \end{pmatrix}.
\end{align*}

Solving $L \mathbf{y} = \mathbf{b}$

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -3 & -1 & 1 \end{pmatrix}
  \begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} = 
  \begin{pmatrix} -7 \\ 11 \\ 1 \end{pmatrix}$$

gives

\begin{align*}
y_1 &= -7, \\ 
y_2 &= 11 - 2y_1 = - 2(-7) = 25, \\ 
y_3 &= -1 + 3y_1 + y_2 = -1 + 3(-7) + 1(25) = 5.
\end{align*}

Solving $U \mathbf{x} = \mathbf{y}$

\begin{align*}
    \begin{pmatrix} 1 & 3 & 0 \\ 0 & -10 & -1 \\ 0 & 0 & 1 \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} &= 
    \begin{pmatrix} -7 \\ 25 \\ 5 \end{pmatrix}
\end{align*}

gives

\begin{align*}
    x_3 &= \frac{1}{1}x_3 = 5, \\
    x_2 &= \frac{1}{-10}(25 + x_3) = -\frac{1}{10}(25+5) = -3, \\
    x_1 &= \frac{1}{1}(-7 - 0x_3 - 3x_2) = -7 + 9 = 2.
\end{align*}

So the solution is $\mathbf{x} = (2, -3, 5)$.

#### Example 4
The function defined below called `crout` solves the linear system of equations $LUx=b$ using Crout's algorithm.

In [3]:
def crout(L, U, b):
    '''
    Calculates the solution to the linear system of equations LUx=b using Crouts
    algorithm
    '''

    # Solve Ly = b using forward substitution
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        for j in range(0, i):
            y[i] += L[i,j] * y[j]
        y[i] = (b[i] - y[i]) / L[i, i]
    
    # Solve Ux = y using back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        for j in range(i, n):
            x[i] += U[i,j] * x[j]
        x[i] = (y[i] - x[i]) / U[i,i]
        
    return x 

The code below uses the function `crout` to solve the linear system of equations from [example 3](#Example-3).

In [4]:
# Define linear system of equations
A = np.array([[1, 3, 0],
              [2, -4, -1],
              [-3, 1, 2 ]])
b = np.array([-7, 11, 1])

# Calculate LU decomposition of A
L, U = LU(A)

# Calculate solution to Ax=b using Crout's algorithm
x = crout(L, U, b)

print('x_1 = {}, x_2 = {}, x_3 = {}'.format(x[0], x[1], x[2]))

x_1 = 2.0, x_2 = -3.0, x_3 = 5.0


---
## Partial pivoting

A problem that can be encountered with LU decomposition is that if the value of $u_{jj}$ in equation [(1)](#LU_lij) is zero or some small number it will mean that $\ell_{ij}$ is undefined or prone to computational rounding errors due to the resulting value being very large (this is known as an [ill-conditioned system](https://en.wikipedia.org/wiki/Condition_number)). 

This problem can be overcome by using [**partial pivoting**](https://en.wikipedia.org/wiki/Pivot_element#Partial_and_complete_pivoting) where rows of the coefficient matrix are permuted so that the pivot element on the main diagonal is the larger than the elements in the column beneath it. The permutations applied to the coefficient matrix are recorded in a matrix $P$ which is determined by applying the same permutations to the identity matrix.

#### Example 5

Apply partial pivotting the following matrix and determine the permutation matrix $P$

$$A = \begin{pmatrix} 0 & 1 & -2 \\ 1 & 0 & 2 \\ 3 & -2 & 2 \end{pmatrix}.$$

Using row operations

\begin{align*}
    \begin{pmatrix} 0 & 1 & -2 \\ 1 & 0 & 2 \\ 3 & -2 & 2 \end{pmatrix}
    R_1 \leftrightarrow R_3 &
    & \longrightarrow &
    & \begin{pmatrix} 3 & -2 & 2 \\ 1 & 0 & 2 \\ 0 & 1 & -2 \end{pmatrix}
    R_2 \leftrightarrow R_3 &
    & \longrightarrow &
    & \begin{pmatrix} 3 & -2 & 2 \\ 0 & 1 & -2 \\ 1 & 0 & 2 \end{pmatrix}
\end{align*}

Applying the same row operations to the identity matrix

\begin{align*}
    \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
    R_1 \leftrightarrow R_3 &
    & \longrightarrow &
    & \begin{pmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\1 & 0 & 0 \end{pmatrix}
    R_2 \leftrightarrow R_3 &
    & \longrightarrow &
    & \begin{pmatrix} 0 & 0 & 1 \\1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}
\end{align*}

So $P = \begin{pmatrix} 0 & 0 & 1 \\1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}$. Note that $PA$ gives the matrix $A$ after partial pivotting has been applied, i.e.,

$$\begin{pmatrix} 0 & 0 & 1 \\1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}
\begin{pmatrix} 0 & 1 & -2 \\ 1 & 0 & 2 \\ 3 & -2 & 2 \end{pmatrix}
=\begin{pmatrix} 3 & -2 & 2 \\ 0 & 1 & -2 \\ 1 & 0 & 2 \end{pmatrix}.$$

#### Example 6

The function defined below called `partial_pivot` calculates the permutation matrix $P$ for applying partial pivotting to the square matrix $A$.

In [5]:
def partial_pivot(A):
    '''
    Applies partial pivotting to A and returns the permutation matrix P
    '''
    n = len(A)
    P = np.eye(n)
    
    # Loop through columns
    for j in range(n):
        
        # Look for max pivot
        maxpivot, k = A[j,j], j
        for i in range (j, n):
            if abs(A[i,j]) > abs(maxpivot):
                maxpivot, k = A[i,j], i
        
        # Swap pivot row with max pivot row
        P[[j,k],:] = P[[k,j],:]
    
    return P

The code below uses the function `partial_pivot` to compute the permutation matrix $P$ for the matrix $A$ from [example 5](#Example-5).

In [6]:
# Define A matrix
A = np.array([[0, 1, -2],
             [1, 0, 2],
             [3, -2, 2]])

# Calculate permutation matrix P
P = partial_pivot(A)
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


---
## LU decomposition with partial pivoting

To calculate **LU decomposition with partial pivoting** uses the process as before with the exception that the coefficient matrix has partial pivotting applied prior to the calculation of $L$ and $U$, i.e.,

$$LU = PA.$$

Using partial pivoting on the coefficient matrix $A$ when solving the linear system of equations $A\mathbf{x}=\mathbf{b}$ results in

$$PA \mathbf{x} = \mathbf{b},$$

and since $P^{-1}=P$ (the inverse operation of swapping any two rows is to simply swap them back) then

$$A \mathbf{x} = P\mathbf{b}.$$

So Crout's algorithm when using LU decomposition with partial pivoting requires solving the following for $\mathbf{y}$ and $\mathbf{x}$.

\begin{align*}
    L\mathbf{y} &= P \mathbf{b}, \\
    U\mathbf{x} &= \mathbf{y}. 
\end{align*}

#### Example 7

Solve the following linear system of equations using Crout's algorithm with LUP decomposition

$$\begin{pmatrix} 0 & 1 & -2 \\ 1 & 0 & 2 \\ 3 & -2 & 2 \end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} = 
\begin{pmatrix} 10 \\ -4 \\ -8 \end{pmatrix}.$$

We have seen from [example 5](#Example-5) that applying partial pivoting to the ceofficient matrix results in

\begin{align*}
    A &= \begin{pmatrix} 3 & -2 & 2 \\ 0 & 1 & -2 \\ 1 & 0 & 2 \end{pmatrix}, &
    P &= \begin{pmatrix} 0 & 0 & 1 \\1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}.
\end{align*}

Calculating the $LU$ decomposition of $A$ using equations [(3) - (5)](#LU)

\begin{align*}
    j &= 1: & u_{11} &= a_{11} = 3, \\
    && \ell_{21} &= \frac{1}{u_{11}}a_{21} = \frac{1}{3}(0) = 0, \\
    && \ell_{31} &= \frac{1}{u_{11}}a_{31} = \frac{1}{3}(1) = \frac{1}{3}, \\
    j &= 2: & u_{12} &= a_{12} = -2, \\
    && u_{22} &= a_{22} - \ell_{21}u_{12} = 1 - 0(-2) = 1, \\
    && \ell_{32} &= \frac{1}{u_{22}}(a_{32} - \ell_{31}u_{12}) = \frac{1}{1}\left(0 - \frac{1}{3}(-2)\right) = \frac{2}{3}, \\
    j &= 3: & u_{13} &= a_{13} = 2, \\
    && u_{23} &= a_{23} - \ell_{21}u_{12} = -2 - 0(-2) = -2, \\
    && u_{33} &= a_{33} - \ell_{31}u_{13} - \ell_{32}u_{23} = 2 - \frac{1}{3}(2) - \frac{2}{3}(-2) = \frac{8}{3}.
\end{align*}

Therefore

\begin{align*}
    L &= \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ \frac{1}{3} & \frac{2}{3} & 1 \end{pmatrix}, &
    R &= \begin{pmatrix} 3 & -2 & 2 \\ 0 & 1 & -2 \\ 0 & 0 & \frac{8}{3} \end{pmatrix}.
\end{align*}

Solving $L\mathbf{y} = P\mathbf{b}$ using forward substitution

\begin{align*}
    \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ \frac{1}{3} & \frac{2}{3} & 1 \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} &= 
    \begin{pmatrix} 0 & 0 & 1 \\1 & 0 & 0 \\ 0 & 1 & 0 \end{pmatrix}
    \begin{pmatrix} 10 \\ -4 \\ -8 \end{pmatrix} = \begin{pmatrix} -8 \\ 10 \\ -4 \end{pmatrix},
\end{align*}

gives

\begin{align*}
    y_1 &= -8, \\
    y_2 &= 10 - 0(8) = 10, \\
    y_3 &= -4 - \frac{1}{3}(8) + \frac{2}{3}(10) = -8.
\end{align*}

Solving $U\mathbf{x}=\mathbf{y}$ using back substitution

\begin{align*}
    \begin{pmatrix} 3 & -2 & 2 \\ 0 & 1 & -2 \\ 0 & 0 & \frac{8}{3} \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} =
    \begin{pmatrix} -8 \\ 10 \\ -8 \end{pmatrix},
\end{align*}

gives


\begin{align*}
    x_3 &= \frac{3}{8}(-8) = -3, \\
    x_2 &= \frac{1}{1}(10 + 2(-3)) = 4, \\
    x_1 &= \frac{1}{3}(-8 + 2(4) - 2(-3)) = 2,
\end{align*}

So the solution is $\mathbf{x}=(2, 4, -3)$.

#### Example 8

The code below uses the previously defined functions `partial_pivot`, `LU` and `crout` to solve the linear system of equations from [example 7](#Example-7) using LU decomposition with partial pivoting.

In [7]:
# Define linear system of equations
A = np.array([[ 0, 1, -2 ],
              [ 1, 0, 2 ],
              [ 3, -2, 2 ]])
b = np.array([ 10, -4, -8 ])

# Calculate permutation matrix P
P = partial_pivot(A)

print('P = ')
print(P)

# Calculate LU decomposition of PA
A = np.matmul(P, A)
L, U = LU(A)

print('\nL = ')
print(L)
print('\nU = ')
print(U)

# Use Crout's algorithm to solve LUx = Pb
Pb = np.matmul(P, b)
x = crout(L, U, Pb)

print('\nx_1 = {}, x_2 = {}, x_3 = {}'.format(x[0], x[1], x[2]))

P = 
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

L = 
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.66666667 1.        ]]

U = 
[[ 3.         -2.          2.        ]
 [ 0.          1.         -2.        ]
 [ 0.          0.          2.66666667]]

x_1 = 2.0, x_2 = 4.0, x_3 = -3.0


---
## Cholesky decomposition

[Cholesky decomposition](https://en.wikipedia.org/wiki/Cholesky_decomposition) is an efficient decomposition method that can be used when a square matrix is [**positive definite**](https://en.wikipedia.org/wiki/Definite_symmetric_matrix). 

> **Definition** A symmetrix square matrix $A$ is said to be positive definite if $\mathbf{x}^T A \mathbf{x}$ is positive for any non-zero column vector $\mathbf{x}$.

Given a positive definite matrix $A$ then Cholesky decomposition factorises $A$ into the product of a lower triangular matrix $L$ and its transpose, i.e.,

$$A = LL^T.$$

Consider the Cholesky decomposition of a $3\times 3$ matrix

\begin{align*}
    \begin{pmatrix}
        a_{11} & a_{12} & a_{13} \\
        a_{21} & a_{22} & a_{23} \\
        a_{31} & a_{32} & a_{33}
    \end{pmatrix} &=
    \begin{pmatrix}
        \ell_{11} & 0 & 0 \\
        \ell_{21} & \ell_{22} & 0 \\
        \ell_{31} & \ell_{32} & \ell_{33}
    \end{pmatrix}
    \begin{pmatrix} 
        \ell_{11} & \ell_{21} & \ell_{31} \\
        0 & \ell_{22} & \ell_{32} \\
        0 & 0 & \ell_{33}
    \end{pmatrix} \\
    &= \begin{pmatrix}
        \ell_{11}^2 & \ell_{11} \ell_{21} & \ell_{11} \ell_{31} \\
        \ell_{11} \ell_{21} & \ell_{21}^2 +  \ell_{22}^2 & \ell_{21} \ell_{31} + \ell_{22} \ell_{33} \\
        \ell_{11} \ell_{31} & \ell_{21} \ell_{31} + \ell_{22} \ell_{33} & \ell_{31}^2 + \ell_{32}^2 + \ell_{33}^2 
    \end{pmatrix}
\end{align*}

The elements of the main diagonal are

$$a_{jj} = \ell_{jj}^2 + \sum_{k=1}^{j-1} \ell_{jk}^2,$$

and the lower triangular elements are 

$$a_{ij} = \sum_{k=1}^j \ell_{ik}\ell_{jk} = \ell_{jj}\ell_{ij} + \sum_{k=1}^{j-1} \ell_{ik} \ell_{jk},$$

Rerranging these two expressions gives

\begin{align*}
    \ell_{jj} &= \sqrt{ a_{jj} - \sum_{k=1}^{j-1} \ell_{jk}^2}, \\
    \ell_{ij} &= \frac{1}{\ell_{jj}} \left( a_{ij} - \sum_{k=1}^{i-1} \ell_{ik} \ell_{jk} \right), & j &= i+1, i+2, \ldots, n.
\end{align*}

#### Example 9

Calculate the Cholesky decomposition of the following matrix

$$A = \begin{pmatrix} 4 & -2 & -4 \\ -2 & 10 & 5 \\ -4 & 5 & 14 \end{pmatrix}.$$

Stepping through the columns of $A$

\begin{align*}
    j &= 1: & \ell_{11} &= \sqrt{a_{11}} = \sqrt{4} = 2, \\
    && \ell_{21} &= \frac{1}{\ell_{11}}(a_{21}) = \frac{1}{2}(-2) = -1, \\
    && \ell_{31} &= \frac{1}{\ell_{11}}(a_{31}) = \frac{1}{2}(-4) = -2, \\
    j &= 2: & \ell_{22} &= \sqrt{a_{22} - \ell_{21}^2} = \sqrt{10 - (-1)^2} = \sqrt{9} = 3, \\
    && \ell_{32} &= \frac{1}{\ell_{22}}(a_{32} - \ell_{31}\ell_{21}) = \frac{1}{3}(5 - (-2)(-1)) = 1, \\
    j &= 3: & \ell_{33} &= \sqrt{a_{33} - \ell_{31}^2 - \ell_{32}^2} = \sqrt{14 - (-2)^2 - 1^2} = \sqrt{9} = 3,
\end{align*}

therefore $L = \begin{pmatrix} 2 & 0 & 0 \\ -1 & 3 & 0 \\ -2 & 1 & 3 \end{pmatrix}$. Checking that $A = LL^T$

\begin{align*}
    \begin{pmatrix} 2 & 0 & 0 \\ -1 & 3 & 0 \\ -2 & 1 & 3 \end{pmatrix}
    \begin{pmatrix} 2 & -1 & -2 \\ 0 & 3 & 1 \\ 0 & 0 & 3 \end{pmatrix} =
    \begin{pmatrix} 4 & -2 & -4 \\ -2 & 10 & 5 \\ -4 & 5 & 14 \end{pmatrix}
\end{align*}

#### Example 10

The function defined below called `cholesky` calculates the Cholesky decomposition of the positive definite matrix $A$. 

In [8]:
def cholesky(A):
    '''
    Calculates the Cholesky decomposition of a positive definite matrix A
    '''
    n = len(A)
    L = np.zeros(A.shape)
    
    # Loop through columns of A
    for j in range(n):
        
        # Calculate main diagonal element
        for k in range(j):
            L[j,j] += L[j,k]**2
        L[j,j] = np.sqrt(A[j,j] - L[j,j])
        
        # Calculate lower triangular elements
        for i in range(j+1, n):
            for k in range(j):
                L[i,j] += L[i,k] * L[j,k]
            L[i,j] = (A[i,j] - L[i,j]) / L[j,j]
    
    return L

The code below uses the function `cholesky` to calculate the Cholesky decomposition of the matrix from [example 9](#Example-9).

In [9]:
# Define matrix A
A = np.array([[4, -2, -4], [-2, 10, 5], [-4, 5, 14]])

# Calculate Cholesky decomposition
L = cholesky(A)

# Output L and check results
print('L = ')
print(L)
print('\nCheck that A - LL.T = 0')
print(A - np.matmul(L, L.T))

L = 
[[ 2.  0.  0.]
 [-1.  3.  0.]
 [-2.  1.  3.]]

Check that A - LL.T = 0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### The Cholesky-Crout method

The [**Cholesky-Crout method**](https://en.wikipedia.org/wiki/Cholesky_decomposition#The_Cholesky%E2%80%93Banachiewicz_and_Cholesky%E2%80%93Crout_algorithms) is used to solve a linear system of equations of the form $A\mathbf{x} = \mathbf{b}$ where $A$ is a positive definite matrix. 

Let $\mathbf{y} = L^T\mathbf{x}$ then since $A=LL^T$ then

\begin{align*}
    L \mathbf{y} &= \mathbf{b},\\
    L^T \mathbf{x} &= \mathbf{y}.
\end{align*}

#### Example 11

Solve the following linear system of equations using the Cholesky-Crout method

$$\begin{pmatrix} 4 & -2 & -4 \\ -2 & 10 & 5 \\ -4 & 5 & 14 \end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} =
\begin{pmatrix} -2 \\ 49 \\ 27 \end{pmatrix}.$$

Solving $L\mathbf{y} = \mathbf{b}$

\begin{align*}
    \begin{pmatrix} 2 & 0 & 0 \\ -1 & 3 & 0 \\ -2 & 1 & 3 \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} =
    \begin{pmatrix} -2 \\ 49 \\ 27 \end{pmatrix},
\end{align*}

gives

\begin{align*}
        y_1 &= \dfrac{-2}{2} = -1, \\
        y_2 &= \dfrac{1}{3}(49 + y_1) = \dfrac{1}{3}(49 - 1) = 16, \\
        y_3 &= \dfrac{1}{3}(27 + 2y_1 - y_2) = \dfrac{1}{3}(27 + 2(-1) -16) = 3.
\end{align*}

Solving $L^T\mathbf{x} = \mathbf{y}$

\begin{align*}
    \begin{pmatrix} 2 & -1 & -2 \\ 0 & 3 & 1 \\ 0 & 0 & 3 \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} &= 
    \begin{pmatrix} -1 \\ 16 \\ 3 \end{pmatrix},
\end{align*}

gives

\begin{align*}
    x_3 &= \frac{3}{3}= 1, \\
    x_2 &= \frac{1}{3}(16 - x_3) = \frac{1}{3}(16 - 1) = 5, \\
    x_1 &= \frac{1}{2}(-1 + x_2 + 2x_3) = \frac{1}{2}(-1 + 5 + 2(1)) = 3,
\end{align*}

So the solution is $\mathbf{x} = (3, 5, 1)$.

#### Example 12

The code below using the functions `cholesky` and `crout` to solve the system of linear equations from [example 11](#Example 11) using the Cholesky-Crout method.

In [13]:
# Define matrix A
A = np.array([[4, -2, -4], [-2, 10, 5], [-4, 5, 14]])
b = np.array([ -2, 49, 27 ])

# Calculate Cholesky decomposition
L = cholesky(A)

# Solve linear system using the Cholesky-Crout method
x = crout(L, L.T, b)

print('x_1 = {}, x_2 = {}, x_3 = {}'.format(x[0], x[1], x[2]))

x_1 = 3.0, x_2 = 5.0, x_3 = 1.0
